curl -H "Content-type: application/json" -d '{"root_directory":"/Users/alfeuduran/Documents/Microsoft/Estudo/CallCenterAnalyticsSample/JsonFiles"}' 'http://localhost:7071/api/orchestrators/E2_BackupSiteContent'
